Add EUID Functionality to Demo Site for CSTG with Prebid.js
IABTechLab/uid2docs pull request #485
Opened 2024-03-06 18:32 UTC by ashleysmithTTD

Extended this page ( http://unifiedid.com/examples/cstg-prebid-example ) to include the ability to generate an EUID advertising token using Prebid.js

2024-03-06 18:49 UTC, ashleysmithTTD commented on static/examples/cstg-prebid-example/index.html
> +        }
Design decision here - for UID2, technically all that needs to be sent is "consentData" -> "getTCData" -> "gdprApplies" but if `consentData` does not have some other properties, the code fails.  So to make it clear what is changing between UID2 and EUID with the "consentManagement" prop, I thought it best to keep the entire object defined and only change if "gdprApplies" is true or false based on the idType

2024-03-19 17:53 UTC, ashleysmithTTD commented on static/examples/cstg-prebid-example/prebid.js
prebid changes are just importing a more updated version of prebid.js

2024-03-20 02:03 UTC, lionell-pack-ttd approved these changes

2024-03-20 02:07 UTC, lionell-pack-ttd requested changes
I hit approve but I realised we're still pointing at the UID2 operator. I think for completeness we should point to EUID integ and create new CSTG keys for this site. I'll add details in comments.

2024-03-20 02:09 UTC, lionell-pack-ttd commented on static/examples/euid-cstg-prebid-example/index.html
> +        EUID_BASE_URL: 'https://operator-integ.uidapi.com',
This is the UID2 integ operator - I think for thoroughness here we should point to EUID infra. The EUID operator is at https://integ.euid.eu

2024-03-20 02:10 UTC, lionell-pack-ttd commented on static/examples/euid-cstg-prebid-example/index.html
> +        SERVER_PUBLIC_KEY: 'UID2-X-I-MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEo+jcPlk8GWn3iG0R5Il2cbFQI9hR3TvHxaBUKHl5Vh+ugr+9uLMiXihka8To07ETFGghEifY96Hrpe5RnYko7Q==',
You'll need to generate new keys for EUID. I'll send you details.

2024-03-22 08:06 UTC, lionell-pack-ttd approved these changes

2024-03-22 16:40 UTC, merged